# Generated by Django 5.1.4 on 2024-12-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(default='', max_length=20)),
                ('usuario_peso', models.IntegerField(default=0)),
                ('usuario_idade', models.IntegerField(default=0)),
                ('meta_dia', models.IntegerField(default=0)),
            ],
        ),
    ]
