# Generated by Django 5.1.4 on 2024-12-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_lembretes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('lembrete_id', models.AutoField(primary_key=True, serialize=False)),
                ('lembrete_dia', models.DateField()),
                ('lembrete_hora', models.TimeField()),
                ('lembrete_quantidade_agua', models.IntegerField()),
                ('usuario_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Lembretes',
        ),
    ]
