# Generated by Django 5.1.4 on 2024-12-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_lembrete_delete_lembretes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='lembrete_mensagem',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='lembrete_dia',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='lembrete_hora',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='lembrete_quantidade_agua',
            field=models.IntegerField(default=0),
        ),
    ]
